### ISSUE TITLE
How to use in vite, plz

### ISSUE THREAD

**Issue by LittleTom** [jambonn/vue-lazyload#3]
GET http://localhost:3000/node_modules/.vite/deps/@jambonn_vue-lazyload.js?v=5ccdfd14 net::ERR_ABORTED 504 (Gateway Timeout)

**Comment by jambonn** [comment]
> GET http://localhost:3000/node_modules/.vite/deps/@jambonn_vue-lazyload.js?v=5ccdfd14 net::ERR_ABORTED 504 (Gateway Timeout)

Currently I still use package with vite. You can try deleting the node_modules folder and start over again
